# config.yaml

# Path to the input CSV file
file_path: "./data/demo.csv"

# Unique identifier to hash
id_column: PIDM

# First and last name columns for de-identification
first_name_column: FIRST_NAME
last_name_column: LAST_NAME

# Number of years to shift dates backward
shift_years: 2

# Categorical columns to anonymize
categorical_columns:
  - MOST_RECENT_STUDENT_LEVEL
  - COLLEGE
  - MAJOR
  - ASTD_STATUS
  - SAP_STATUS

# Semester columns in YYYYMM format to shift
semester_columns:
  - COHORT
  - GRAD_TERM
  - MOST_RECENT_TERM_ENROLLED

# Email and phone columns for de-identification
email_column: EMAIL
phone_column: PHONE

# Another ID column to hash for consistency
student_id_column: PANTHERID

# Integer columns to adjust randomly by +/- 1
integer_columns:
  - HOURS_EARNED

# Float columns to adjust randomly by +/- 0.25
float_columns:
  - OUTSTANDING_FINANCIAL_BALANCE
  - INSTITUTIONAL_GPA
  - OVERALL_GPA